version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=vulnerability_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Chino01*
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Chino01*@db:5432/vulnerability_manager
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

volumes:
  postgres_data:
